apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.name }}"
  namespace: {{ .Release.Namespace }}
  labels:
    app: "{{ .Values.name }}"
spec:
  ports:
  - port: {{ .Values.redis_stack_server.port }}
    name: db
  type: NodePort
  selector:
    app: "{{ .Values.name }}"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: "{{ .Values.name }}"
spec:
  selector:
    matchLabels:
      app: "{{ .Values.name }}" 
  serviceName: "{{ .Values.name }}"
  replicas: {{ .Values.redis_stack_server.replicas }}
  template:
    metadata:
      labels:
        app: "{{ .Values.name }}" 
    spec:
      containers:
      - env:
        - name: REDIS_ARGS
          valueFrom:
            secretKeyRef:
              key: REDIS_ARGS
              name: redis-secret-klone-detect
        name: "{{ .Values.name }}"
        image: {{ .Values.redis_stack_server.image }}:{{ .Values.redis_stack_server.tag }}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.redis_stack_server.port }}
          name: db
        volumeMounts:
        - name: db
          mountPath: /data
      terminationGracePeriodSeconds: 10
  volumeClaimTemplates:
  - metadata:
      name: db
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: {{ .Values.redis_stack_server.storage_class }}
      resources:
        requests:
          storage: {{ .Values.redis_stack_server.storage }}
